M48
; DRILL file {KiCad 8.0.5} date 2025-02-13T07:49:34+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-13T07:49:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T1
X5.922Y-4.068
T2
X3.1913Y-4.4732
X3.5457Y-4.4732
M30
