M48
; DRILL file {KiCad 8.0.0} date 2024-03-15T11:34:27+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-15T11:34:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X7.0215Y-2.8451
X7.0215Y-3.0726
T2
X7.3077Y-3.2448
X7.4258Y-3.2448
T3
X7.3421Y-2.9075
M30
